spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_firstsboot
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true




#server:
  #port: 8080
  #context-path: /

#name: test
#height: 180
#object: "name:${name},height:${height}"
#
#objs:
  #name: test
  #height: 170
